### ISSUE TITLE
not able to add user

### ISSUE THREAD

**Issue by anushaGundapaneni** [servntire/Property-Registry#1]
hi,
i completed total process as how you described but i am not able to create add user. no pop up is happened while doing add user. in add user "user address field i gave my metamask account address" then after i clicked on add field but no popup appeared. please tell me how to solve it 

below is my screenshot after filling details 
(recent:///5d2ffd896c0ed23c65e66e9e5b7a67fd)]

**Comment by anushaGundapaneni** [comment]
![screenshot from 2018-08-20 12 34 10](https://user-images.githubusercontent.com/31063969/44325221-c9e29a00-a475-11e8-9f25-e64ee5d4c591.png)
this is my screen shot after filling details

**Comment by muntahanoor** [comment]
I am getting a problem in adding user or admin, what type of values can be used in this form
![problem](https://user-images.githubusercontent.com/50441328/65322159-e2325600-db5a-11e9-87b3-1b0f6ce67c6d.PNG)

**Comment by saadibrahimiv** [comment]
same issue happening with me. i have chnaged ABI and gave the contract address in app.js but the app is not communicating with the contract. i can't add user and no pop up opens in meta mask for transaction. i'm trying to do it with the same account with which the contract was deployed.

**Comment by saadibrahimiv** [comment]
> hi,
> i completed total process as how you described but i am not able to create add user. no pop up is happened while doing add user. in add user "user address field i gave my metamask account address" then after i clicked on add field but no popup appeared. please tell me how to solve it
> 
> below is my screenshot after filling details
> (recent:///5d2ffd896c0ed23c65e66e9e5b7a67fd)]

did you solve it?

**Comment by sachushaji** [comment]
You should be able to add the user with recent #7 update
