### ISSUE TITLE
how to execute

### ISSUE THREAD

**Issue by vineeth0911** [servntire/Property-Registry#4]
how to execute the index.html all the process has successfully done. But unable to execute the index.html file into the browser. please help me asap

**Comment by tittuvarghese** [comment]
If you have PHP CLI, then
`cd /path/to/project`
`php -S localhost:8000`
open browser and visit localhost:8000

Or use any of the local servers like WAMP / XAMPP and copy the files to it and serve.

**Comment by vineeth0911** [comment]
does it require any cmd commands like npm start run
or
any ng server tools

**Comment by vineeth0911** [comment]
please any one respond me..!!!!

**Comment by vineeth0911** [comment]
how to execute this file i could not get it. any changes need to done for truffle.js file

**Comment by sachushaji** [comment]
The app has been updated to make it a bit easier to load the webapp. I have updated the instructions. But the UI is a bit poor, Anybody interested can do a PR for it ;-)
